name: Main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.10"]
        JOBLIB_VERSION: ["1.3.2", "1.4.2"]
        PYSPARK_VERSION: ["3.4.4", "3.5.5", "4.0.0.dev2"]
        SPARK_CONNECT_MODE: [false, true]
        exclude:
          - PYSPARK_VERSION: "3.4.4"
            SPARK_CONNECT_MODE: true
          - PYSPARK_VERSION: "3.5.5"
            SPARK_CONNECT_MODE: true
    name: Run test on pyspark ${{ matrix.PYSPARK_VERSION }}, Use Spark Connect ${{ matrix.SPARK_CONNECT_MODE }}, joblib ${{ matrix.JOBLIB_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: x64
      - name: Install python packages
        run: |
          pip install joblib==${{ matrix.JOBLIB_VERSION }} scikit-learn>=0.23.1 pytest pylint "pyspark[connect]==${{ matrix.PYSPARK_VERSION }}" pandas
      - name: Run test suites
        run: |
          TEST_SPARK_CONNECT=${{ matrix.SPARK_CONNECT_MODE }} PYSPARK_VERSION=${{ matrix.PYSPARK_VERSION }} ./run-tests.sh
      - name: Run pylint
        run: |
          ./run-pylint.sh
