name: Main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.11", "3.12"]
        JOBLIB_VERSION: ["1.3.0", "1.4.2"]
        PIN_MODE: [false, true]
        PYSPARK_VERSION: ["4.0.0.dev1"]
    name: Run test with spark connect ${{ matrix.PYSPARK_VERSION }}, pin_mode ${{ matrix.PIN_MODE }}, python ${{ matrix.PYTHON_VERSION }}, joblib ${{ matrix.JOBLIB_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: x64
      - name: Install python packages
        run: |
          pip install setuptools joblib==${{ matrix.JOBLIB_VERSION }} scikit-learn>=0.23.1 pytest pylint 
          pip install 'numpy==1.26.4' 'pyarrow==12.0.1' 'pandas<=2.0.3'
          # Add Python deps for Spark Connect.
          pip install 'grpcio>=1.48,<1.57' 'grpcio-status>=1.48,<1.57' 'protobuf==3.20.3' 'googleapis-common-protos==1.56.4'
          pip install "pyspark[connect]==${{ matrix.PYSPARK_VERSION }}"
      - name: Run pylint
        run: |
          ./run-pylint.sh
      - name: Run test suites
        run: |
          PYSPARK_PIN_THREAD=${{ matrix.PIN_MODE }} ./run-tests.sh
